const employees = [
  {
    id: 1,
    firstname: "Atharva",
    email: "e@e.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Update Website UI",
        description: "Improve the homepage layout with modern UI",
        date: "2025-08-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Fix Navbar Bug",
        description: "Navbar doesn't collapse on mobile",
        date: "2025-07-30",
        category: "Bug Fix",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Research Tailwind CSS",
        description: "Understand Tailwind utility classes for upcoming project",
        date: "2025-07-25",
        category: "Learning",
        active: true,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    firstname: "Ishita",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Backend API Integration",
        description: "Connect frontend with backend APIs",
        date: "2025-08-01",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Unit Testing",
        description: "Write unit tests for auth module",
        date: "2025-07-29",
        category: "Testing",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Documentation",
        description: "Document all project endpoints",
        date: "2025-07-26",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: true,
      },
      {
        title: "Slack Bot Setup",
        description: "Integrate daily reminder bot for standups",
        date: "2025-08-01",
        category: "Automation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstname: "Rohan",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Client Feedback Review",
        description: "Review client feedback for latest delivery",
        date: "2025-07-31",
        category: "Management",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Fix Login Error",
        description: "Resolve unexpected logout issue",
        date: "2025-07-30",
        category: "Bug Fix",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Code Refactor",
        description: "Refactor user module for better performance",
        date: "2025-07-27",
        category: "Code Cleanup",
        active: true,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    firstname: "Meera",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Create Onboarding Slides",
        description: "Slides for new interns' onboarding",
        date: "2025-08-01",
        category: "Training",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Weekly Report",
        description: "Generate performance report for last week",
        date: "2025-07-29",
        category: "Report",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Server Load Test",
        description: "Test backend performance under heavy load",
        date: "2025-07-28",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: true,
      },
      {
        title: "Mentor Junior Devs",
        description: "Weekly mentorship session with interns",
        date: "2025-07-30",
        category: "Management",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstname: "Neeraj",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "SEO Optimization",
        description: "Improve website SEO with meta tags",
        date: "2025-08-01",
        category: "Marketing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Blog Post Writing",
        description: "Write blog on recent tech trends",
        date: "2025-07-30",
        category: "Content",
        active: true,
        newTask: true,
        completed: true,
        failed: false,
      },
      {
        title: "Image Optimization",
        description: "Compress and optimize product images",
        date: "2025-07-27",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 101,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
